### ISSUE TITLE
Figure out how to edit content json files

### ISSUE THREAD

**Issue by jhagberg** [NBISweden/encam#116]
Manual for updating content json file?

**Comment by jhagberg** [comment]
Using /admin

**Comment by HenrikeW** [comment]
@ArturMezh We checked this issue and for us, it works to edit the `content.json` file via the editor on `encima.one/admin`.
Do you still have problems with that?
If I understood it right, you would like to have a manual or user documentation for this. I can easily make that but it would be nice to know what exactly it is you have problems with (if there are any). It would help me to know how detailed you want need the documentation to be. 
Also, in which format and where would you like to have it? One option would be to add it to this repo in the "Wiki" section. What do you think about that?

**Comment by ArturMezh** [comment]
@HenrikeW Hello. There is no problems, just I am not a computer engineer, and what looks simple for you is completely not obvious for me.
For example, I can see how I can change/add some text. But for example, can I change background colour and size of the panels etc?
Well, I would need very brief description. Probably its OK to do it with several screenshots etc. and short explanation. I dont know what is Wiki section, but it will probably work, if you recommend.

**Comment by HenrikeW** [comment]
Okay, thanks for the reply @ArturMezh ! I can perfectly understand that it's not obvious, and what you write already helps me a lot. I will make a draft explanation with some screenshots and then you can have a look at it and I can improve whatever is still unclear by then.

**Comment by HenrikeW** [comment]
@ArturMezh I've now added some instructions for how to use the admin editor to the Wiki page of this GitHub repository. You can find them here: https://github.com/NBISweden/encam/wiki/Admin-manual
Does this help you?
If there are still open questions, can you specify which parts need more detailed instructions?
