### ISSUE TITLE
Box plots & group boxplots issues from Artur

### ISSUE THREAD

**Issue by danr** [NBISweden/encam#69]
* [x] It seems like visualization is too large for the view. We can not fix it completely I think, but we can improve:
    - [x] Maybe try to make the ‘filter’ a bit more compact in horizontal dimension especially. May be not possible..
    - [ ] There is no obvious ‘mover’ or how is it called, to move the view. On touch-screen (mobile view) it is intuitively to do by touch and fingers. On screen is works well is one has touch screen. Otherwise not convenient.
    - [x] Make as default the ‘portrait’ view.
    - [x] Could you make a ‘visible cells’ panel horizontal, just above the main plot? It is taking too much horizontal space.. 

* [x] Similarly to starting page – we need simple icon showing what is tumor and what is stroma
* [x] Is relation to the issues above – it seems like the order of the tumors, presented on the Grouped box plots is always alphabetical. It would be easier to read if it would rather follow the selection order in the ‘filters’.. So it would show the second filter data below the first filter data. 

* [x] For Grouped box plots – could you make the colours on the group filtering panels corresponding the colour code on the graph. Now the colour in filters is dark blue everywhere.
* [x] For Grouped box plots – limit the selection to only ONE group in each of two filter panels.
* [ ] [additionally to this – but not mandatory, this is rather issue to discuss.. would it be possible to add below some option to add third (fourth) filter panel in case one needs to compare more than two groups? If complicated we just keep it limited to two at the same time]
* [x] Sort cells in the plot in the same order as the starting page splash.

**Comment by danr** [comment]
* [x] Sort tumors alphabetically in dropdown
* [x] Sort group A before B in the plot

**Comment by danr** [comment]
* [x] For Grouped box plots – limit the selection to only ONE group in each of two filter panels. This means: Max 1 cell or tumor type per group. OK to make a radio button to toggle between cell & tumor

**Comment by danr** [comment]
Boxplots:
* [x] Show legend for stroma/tumor 
* [x] Revive boxplots without groups

**Comment by danr** [comment]
* [ ] Don't allow plot when no types are selected
* [ ] What to do when the filter returned nothing? ...

**Comment by dbampalikis** [comment]
I am not sure if you are looking for feedback, but I think it would make sense to let the user know that the search criteria are not returning any results

**Comment by danr** [comment]
* [x] Now, in made up dataset we have location and morph type specified only for COAD and READ, but in reality it will be for other cancers also… Can it be somehow condensed in some kind of unfolding menu? #60 

![image](https://user-images.githubusercontent.com/199380/86233199-5e9ba000-bb95-11ea-9d2f-01304bd438e8.png)
