### ISSUE TITLE
CMS & Updateable texts

### ISSUE THREAD

**Issue by danr** [NBISweden/encam#94]
### Setup with login system

- Login using google auth
    - Hardcoded whitelist of accepted accounts 
- Start making changes, they are stored in a staging area
- Endpoint: `contents.staged.json` with both GET & POST
- When you want it to be published, press PUBLISH!
   - frontend could call POST to `contents.json`  
- Optional: save a local copy of `contents.json` to version control
- Optional: for backup: push to a repo. use restricted token to auth to github 
- Add `/admin`, the javascript router will take care of it, but need to configure nginx to route that to index.html, this might be enough: https://github.com/NBISweden/theherdbook/pull/177/commits/3a909b8c7a4bfa1e5f11715698f2c36314117b33

### Setup without login system
_we will not do this but saving it for reference_

- Artur connects to a dev server (without logging in)
- He edits some of the text fields
- Saves `content.json` locally

How to get it to prod?
- Artur saves the file to a git repo and pushes
- Github webhook: https://docs.github.com/en/free-pro-team@latest/developers/webhooks-and-events/about-webhooks
   - which calls an endpoint on the server.

**Comment by dbampalikis** [comment]
@danr can we close this?

**Comment by danr** [comment]
Yes, this is finished with #100.
